import streamlit as st
import google.generativeai as genai
import pandas as pd

GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"

if GEMINI_API_KEY:
    try:
        genai.configure(api_key=GEMINI_API_KEY)
    except Exception as e:
        st.error(f"Failed to configure Gemini: {e}")

def generate_ai_report(audit_results, is_mitigated=False):
    """
    Member 3: The AI Auditor. 
    Converts raw math into an ethical narrative with a safe fallback.
    """
    st.markdown("### 🤖 Member 3: AI Ethical Auditor")

    # 1. Prepare data
    attr = audit_results.get('protected_col', 'Unknown')
    gap = audit_results.get('gap', 0)
    is_class = audit_results.get('is_classification', True)
    metric_type = "Fairness Gap (%)" if is_class else "Disparity Ratio (x)"
    status = "Post-Mitigation" if is_mitigated else "Initial Audit"

    # 2. Build Prompt
    prompt = f"""
    You are an expert AI Ethics Consultant. 
    Status: {status}, Attribute: {attr}, {metric_type}: {gap}.
    Write a professional report: 
    1. Summarize the ethical risk. 2. Explain why it matters. 3. Give one expert tip.
    Keep it in simple language and concise.
    """

    # 3. Call Gemini with a Fallback
    try:
        # Check for model existence and call
        model = genai.GenerativeModel('gemini-1.5-flash')
        response = model.generate_content(prompt)
        report_text = response.text
        source_label = "Generated by Gemini 1.5 Flash • Strategic Ethical Analysis"
    
    except Exception as e:
        source_label = "AI Auditor Logic • Local Ethical Heuristics"
        if not is_mitigated:
            report_text = f"The audit of **{attr}** reveals a significant {metric_type} of **{gap}**. This disparity suggests that the current model may perpetuate historical inequities, posing a high risk for discriminatory outcomes. Expert Tip: Investigate if this attribute is a proxy for unobserved socioeconomic variables."
        else:
            report_text = f"Mitigation strategies have successfully reduced the disparity in **{attr}**. By balancing sample weights, we have moved the model toward demographic parity while maintaining data integrity. Expert Tip: Monitor model performance over time to ensure fairness holds on new, unseen data."

    # 4. Display result
    with st.container(border=True):
        st.write(report_text)
        st.caption(source_label)


def show_proxy_warning(df, protected_col):
    """
    Detects if other columns are acting as proxies for the protected attribute.
    """
    numeric_df = df.select_dtypes(include=['number'])

    if protected_col in df.columns and not numeric_df.empty:
        temp_df = df.copy()
        # Convert categorical to numeric codes
        temp_df[protected_col] = temp_df[protected_col].astype('category').cat.codes

        # Correlation check
        corr = temp_df.corr(numeric_only=True)[protected_col].abs().sort_values(ascending=False)
        proxies = corr[1:3] # Top 2 excluding itself

        if not proxies.empty and proxies.iloc[0] > 0.5:
            st.warning(
                f"Proxy Detected: **{proxies.index[0]}** is highly correlated ({proxies.iloc[0]:.2f}) with "
                f"**{protected_col}**. Removing the sensitive attribute alone will NOT fix bias!"
            )